# Autogenerated wrapper script for spdlog_jll for aarch64-apple-darwin
export libspdlog

using Fmt_jll
JLLWrappers.@generate_wrapper_header("spdlog")
JLLWrappers.@declare_library_product(libspdlog, "@rpath/libspdlog.1.14.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Fmt_jll)
    JLLWrappers.@init_library_product(
        libspdlog,
        "lib/libspdlog.1.14.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
